name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
      - run: chmod +x gradlew
      - run: ./gradlew setupCIWorkspace build
      - uses: actions/upload-artifact@v4
        with:
          name: bridgetrainer-jar
          path: build/libs/*.jar
